import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary": "#482727",
        "surface-container-low": "#1e1b19",
        "on-secondary-container": "#dba9a7",
        "on-tertiary-fixed": "#002022",
        "on-primary-container": "#ff978d",
        "inverse-primary": "#a03e38",
        "on-secondary-fixed": "#301313",
        "on-primary-fixed-variant": "#812723",
        "secondary-fixed-dim": "#edbab8",
        "primary-fixed": "#ffdad6",
        "surface-container-lowest": "#100e0c",
        "surface-tint": "#ffb4ac",
        "primary-fixed-dim": "#ffb4ac",
        "outline": "#a48b88",
        "primary": "#ffb4ac",
        "surface-container-highest": "#383432",
        "on-surface-variant": "#dcc0bd",
        "tertiary-fixed-dim": "#94d1d5",
        "surface-bright": "#3c3836",
        "surface-container": "#221f1d",
        "outline-variant": "#564240",
        "on-tertiary-fixed-variant": "#024f53",
        "surface-container-high": "#2d2927",
        "surface-variant": "#383432",
        "error": "#ffb4ab",
        "primary-container": "#7f2622",
        "error-container": "#93000a",
        "secondary": "#edbab8",
        "on-primary-fixed": "#410003",
        "on-secondary-fixed-variant": "#623d3c",
        "surface-dim": "#161311",
        "pure-black": "#000000",
        "on-tertiary-container": "#81bec2",
        "on-error-container": "#ffdad6",
        "tertiary-container": "#004e52",
        "secondary-container": "#623d3c",
        "on-surface": "#e9e1dd",
        "tertiary-fixed": "#b0edf2",
        "inverse-on-surface": "#33302d",
        "pure-white": "#FFFFFF",
        "secondary-fixed": "#ffdad8",
        "on-tertiary": "#00373a",
        "technical-gray": "#3D3D3D",
        "tertiary": "#94d1d5",
        "on-error": "#690005",
        "inverse-surface": "#e9e1dd",
        "on-primary": "#62100f",
        "surface": "#161311",
        "background": "#FFFFFF",
        "on-background": "#161311",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "annotation-gap": "8px",
        "section-v-mobile": "80px",
        "section-v-tablet": "100px",
        "section-v-desktop": "160px",
        "grid-gutter": "24px",
        "container-margin": "64px",
      },
      fontFamily: {
        "label-metric": ["var(--font-geist)", "Geist", "sans-serif"],
        "label-technical": ["var(--font-geist)", "Geist", "sans-serif"],
        "body-md": ["var(--font-manrope)", "Manrope", "sans-serif"],
        "body-lg": ["var(--font-manrope)", "Manrope", "sans-serif"],
        "headline-xl": ["var(--font-manrope)", "Manrope", "sans-serif"],
        "headline-lg-mobile": ["var(--font-manrope)", "Manrope", "sans-serif"],
        "headline-md": ["var(--font-manrope)", "Manrope", "sans-serif"],
        "headline-lg": ["var(--font-manrope)", "Manrope", "sans-serif"],
      },
      fontSize: {
        "label-metric": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-technical": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" }],
        "body-md": ["17px", { lineHeight: "28px", fontWeight: "400" }],
        "body-lg": ["20px", { lineHeight: "32px", fontWeight: "400" }],
        "headline-xl": ["88px", { lineHeight: "96px", letterSpacing: "-0.04em", fontWeight: "800" }],
        "headline-lg-mobile": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["44px", { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["64px", { lineHeight: "72px", letterSpacing: "-0.03em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};

export default config;
